#config_version=4

switches:
  s_left_flipper:
    number:
    tags: left_flipper
  s_right_flipper:
    number:
    tags: right_flipper
coils:
  c_flipper_left_main:
    number: 0
    pulse_ms: 20 # movement speed of flipper - lower is faster
  c_flipper_left_hold:
    number: 1
    allow_enable: true
  c_flipper_right_main:
    number: 2
    pulse_ms: 20
  c_flipper_right_hold:
    number: 3
    allow_enable: true
flippers:
  left_flipper:
    main_coil: c_flipper_left_main
    hold_coil: c_flipper_left_hold
    activation_switch: s_left_flipper
    enable_events: machine_reset_phase_3 #temp to test flippers
  right_flipper:
    main_coil: c_flipper_right_main
    hold_coil: c_flipper_right_hold
    activation_switch: s_right_flipper
    enable_events: machine_reset_phase_3 #temp to test flippers
